"""GitHub PR opener — commits fixes to a branch and opens a pull request.

Enforces the human approval gate: the PR requires human review and merge.
SentinelAI never self-merges.

Requires environment variables:
    GITHUB_TOKEN: GitHub personal access token (with repo scope)
    GITHUB_REPO: Repository in owner/repo format
"""

from __future__ import annotations

import logging
import os
import subprocess
from datetime import UTC, datetime
from pathlib import Path

import httpx

from sentinelai.contracts.pr_opener import PROpener
from sentinelai.core.errors import PRCreationError
from sentinelai.core.events import FixGenerated, PROpened, TriageComplete

logger = logging.getLogger("sentinelai.pr_openers.github")


def _run_git(args: list[str], cwd: str) -> str:
    """Run a git command and return stdout. Raises PRCreationError on failure."""
    try:
        result = subprocess.run(
            ["git", *args],
            cwd=cwd,
            capture_output=True,
            text=True,
            timeout=30,
        )
    except FileNotFoundError as e:
        raise PRCreationError(f"git not found on PATH: {e}") from e
    except subprocess.TimeoutExpired as e:
        raise PRCreationError(f"git {' '.join(args)} timed out after 30s") from e

    if result.returncode != 0:
        raise PRCreationError(f"git {' '.join(args)} failed: {result.stderr.strip()}")

    return result.stdout.strip()


class GitHubPROpener(PROpener):
    """Opens GitHub PRs with AI-generated fixes.

    Workflow:
    1. Create a feature branch: sentinelai/fix-{alert_id}-{timestamp}
    2. Write fixed files and test file to disk
    3. Commit changes with descriptive message
    4. Push branch to origin
    5. Open PR via GitHub API with full context
    """

    def __init__(self) -> None:
        self._token = os.environ.get("GITHUB_TOKEN", "")
        self._repo = os.environ.get("GITHUB_REPO", "")

    async def open_pr(
        self,
        fix: FixGenerated,
        triage: TriageComplete,
        repo_path: str,
    ) -> PROpened:
        if not self._token:
            raise PRCreationError("GITHUB_TOKEN not set", trace_id=fix.trace_id)
        if not self._repo:
            raise PRCreationError("GITHUB_REPO not set", trace_id=fix.trace_id)

        # Step 1: Create branch
        ts = datetime.now(UTC).strftime("%Y%m%d-%H%M%S")
        branch_name = f"sentinelai/fix-{fix.alert_id}-{ts}"

        _run_git(["checkout", "-b", branch_name], cwd=repo_path)

        try:
            # Step 2: Write fixes to disk
            for code_fix in fix.fixes:
                file_path = Path(repo_path) / code_fix.file_path
                file_path.parent.mkdir(parents=True, exist_ok=True)
                file_path.write_text(code_fix.fixed_content)
                _run_git(["add", code_fix.file_path], cwd=repo_path)

            # Step 3: Write test file
            if fix.test_code:
                test_path = Path(repo_path) / fix.test_file_path
                test_path.parent.mkdir(parents=True, exist_ok=True)
                test_path.write_text(fix.test_code)
                _run_git(["add", fix.test_file_path], cwd=repo_path)

            # Step 4: Commit
            commit_msg = (
                f"fix: [{triage.severity.value}] {triage.root_cause_hypothesis[:80]}\n\n"
                f"Auto-generated by SentinelAI for alert {fix.alert_id}.\n"
                f"Confidence: {fix.confidence:.0%}\n\n"
                f"Rationale:\n{fix.rationale}\n\n"
                f"Co-Authored-By: SentinelAI <sentinelai@noreply>"
            )
            _run_git(["commit", "-m", commit_msg], cwd=repo_path)

            # Step 5: Push
            _run_git(["push", "-u", "origin", branch_name], cwd=repo_path)

            # Step 6: Open PR via GitHub API
            pr_result = await self._create_pr(fix, triage, branch_name)

            logger.info(
                "Pull request opened",
                extra={
                    "trace_id": fix.trace_id,
                    "alert_id": fix.alert_id,
                    "pr_number": pr_result.pr_number,
                    "pr_url": pr_result.pr_url,
                    "branch": branch_name,
                    "event": "pr.opened",
                },
            )

            return pr_result

        except PRCreationError:
            # Try to clean up: switch back to previous branch
            try:
                _run_git(["checkout", "-"], cwd=repo_path)
            except PRCreationError:
                pass
            raise

    async def _create_pr(
        self,
        fix: FixGenerated,
        triage: TriageComplete,
        branch_name: str,
    ) -> PROpened:
        """Create a PR via GitHub REST API."""
        files_changed = "\n".join(f"- `{f.file_path}`: {f.description}" for f in fix.fixes)

        body = (
            f"## SentinelAI Auto-Fix\n\n"
            f"**Alert:** {fix.alert_id}\n"
            f"**Severity:** {triage.severity.value}\n"
            f"**Confidence:** {fix.confidence:.0%}\n\n"
            f"### Root Cause\n{triage.root_cause_hypothesis}\n\n"
            f"### What Changed\n{files_changed}\n\n"
            f"### Rationale\n{fix.rationale}\n\n"
            f"### Test Plan\n"
            f"- AI-generated test at `{fix.test_file_path}`\n"
            f"- Run: `pytest {fix.test_file_path}`\n\n"
            f"### Rollback\n{fix.rollback_instructions}\n\n"
            f"---\n"
            f"*This PR was auto-generated by SentinelAI. It requires human approval before merge.*\n"
            f"*Trace: {fix.trace_id}*"
        )

        payload = {
            "title": f"[{triage.severity.value}] fix: {triage.root_cause_hypothesis[:80]}",
            "body": body,
            "head": branch_name,
            "base": "main",
        }

        async with httpx.AsyncClient(timeout=30.0) as client:
            try:
                resp = await client.post(
                    f"https://api.github.com/repos/{self._repo}/pulls",
                    json=payload,
                    headers={
                        "Authorization": f"Bearer {self._token}",
                        "Accept": "application/vnd.github.v3+json",
                        "X-GitHub-Api-Version": "2022-11-28",
                    },
                )
            except httpx.TimeoutException as e:
                raise PRCreationError(f"GitHub API timeout: {e}", trace_id=fix.trace_id) from e
            except httpx.HTTPError as e:
                raise PRCreationError(f"GitHub API error: {e}", trace_id=fix.trace_id) from e

        if resp.status_code not in (200, 201):
            raise PRCreationError(
                f"GitHub PR creation failed ({resp.status_code}): {resp.text[:300]}",
                trace_id=fix.trace_id,
            )

        data = resp.json()
        return PROpened(
            alert_id=fix.alert_id,
            pr_number=data.get("number", 0),
            pr_url=data.get("html_url", ""),
            branch_name=branch_name,
            trace_id=fix.trace_id,
        )
