"""Domain events for the SentinelAI pipeline.

Event flow:
    AlertDetected ──► TriageComplete ──► (console output in Phase 1)
                                         (TicketCreated in Phase 1.5+)

All events are treated as immutable after creation. Fields are not frozen
because raw_payload is a dict (unhashable), but callers must not mutate events.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import Enum


class Priority(Enum):
    """Alert severity classification.

    P1 = service down, P2 = degraded, P3 = non-critical, P4 = cosmetic.
    UNKNOWN = AI triage failed or timed out — requires manual review.
    """

    P1 = "P1"
    P2 = "P2"
    P3 = "P3"
    P4 = "P4"
    UNKNOWN = "UNKNOWN"


@dataclass
class AlertDetected:
    """An alert has been received from an alert source plugin.

    Fields:
        alert_id: Unique identifier, also used as dedup key component.
        source: Name of the plugin that produced this alert.
        service_name: Affected service identifier.
        summary: One-line description of the alert.
        raw_payload: Provider-specific raw alert data (untyped — see AlertContext TODO).
        timestamp: UTC timestamp of when the alert was ingested.
        trace_id: Correlation ID for structured logging. Generated by pipeline orchestrator (UUID4).
    """

    alert_id: str
    source: str
    service_name: str
    summary: str
    raw_payload: dict
    timestamp: datetime = field(default_factory=lambda: datetime.now(UTC))
    trace_id: str = ""


@dataclass
class TriageComplete:
    """AI triage has completed for an alert.

    Fields:
        alert_id: Links back to the originating AlertDetected.
        severity: P1-P4 or UNKNOWN if triage failed.
        root_cause_hypothesis: AI-generated root cause analysis.
        confidence: 0.0-1.0 confidence score from the AI model.
        affected_services: Services the AI identified as impacted.
        recommended_action: AI-suggested remediation step.
        ai_reasoning: Full reasoning chain for audit trail and `sentinelai explain`.
        trace_id: Propagated from AlertDetected.
    """

    alert_id: str
    severity: Priority
    root_cause_hypothesis: str
    confidence: float
    affected_services: list[str]
    recommended_action: str
    ai_reasoning: str
    trace_id: str = ""
