"""Domain events for the SentinelAI pipeline.

Event flow:
    AlertDetected ──► TriageComplete ──► TicketCreated
                                    └──► FixGenerated ──► PROpened
                                                           │
                                                    [Human Approval]
                                                           │
                                                       PRMerged (Phase 3+)

All events are treated as immutable after creation. Fields are not frozen
because raw_payload is a dict (unhashable), but callers must not mutate events.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import Enum


class Priority(Enum):
    """Alert severity classification.

    P1 = service down, P2 = degraded, P3 = non-critical, P4 = cosmetic.
    UNKNOWN = AI triage failed or timed out — requires manual review.
    """

    P1 = "P1"
    P2 = "P2"
    P3 = "P3"
    P4 = "P4"
    UNKNOWN = "UNKNOWN"


@dataclass
class AlertDetected:
    """An alert has been received from an alert source plugin.

    Fields:
        alert_id: Unique identifier, also used as dedup key component.
        source: Name of the plugin that produced this alert.
        service_name: Affected service identifier.
        summary: One-line description of the alert.
        raw_payload: Provider-specific raw alert data (untyped — see AlertContext TODO).
        timestamp: UTC timestamp of when the alert was ingested.
        trace_id: Correlation ID for structured logging. Generated by pipeline orchestrator (UUID4).
    """

    alert_id: str
    source: str
    service_name: str
    summary: str
    raw_payload: dict
    timestamp: datetime = field(default_factory=lambda: datetime.now(UTC))
    trace_id: str = ""


@dataclass
class TriageComplete:
    """AI triage has completed for an alert.

    Fields:
        alert_id: Links back to the originating AlertDetected.
        severity: P1-P4 or UNKNOWN if triage failed.
        root_cause_hypothesis: AI-generated root cause analysis.
        confidence: 0.0-1.0 confidence score from the AI model.
        affected_services: Services the AI identified as impacted.
        recommended_action: AI-suggested remediation step.
        ai_reasoning: Full reasoning chain for audit trail and `sentinelai explain`.
        trace_id: Propagated from AlertDetected.
    """

    alert_id: str
    severity: Priority
    root_cause_hypothesis: str
    confidence: float
    affected_services: list[str]
    recommended_action: str
    ai_reasoning: str
    affected_files: list[str] = field(default_factory=list)  # Fault-domain files identified by triage
    trace_id: str = ""


@dataclass
class CodeFix:
    """A single file change generated by the code fixer.

    Fields:
        file_path: Relative path to the file being modified.
        original_content: The file content before the fix (for diff generation).
        fixed_content: The file content after the fix.
        description: One-line description of what this change does.
    """

    file_path: str
    original_content: str
    fixed_content: str
    description: str


@dataclass
class FixGenerated:
    """AI has generated a code fix for a triaged alert.

    Fields:
        alert_id: Links back to the originating alert.
        fixes: List of file changes that constitute the fix.
        test_code: AI-generated test code that validates the fix.
        test_file_path: Where to write the generated test file.
        rationale: AI explanation of what was wrong and why this fix is correct.
        confidence: 0.0-1.0 confidence in the fix quality.
        rollback_instructions: How to revert this fix if it causes problems.
        trace_id: Propagated from TriageComplete.
    """

    alert_id: str
    fixes: list[CodeFix]
    test_code: str
    test_file_path: str
    rationale: str
    confidence: float
    rollback_instructions: str
    trace_id: str = ""


@dataclass
class PROpened:
    """A pull request has been created with the AI-generated fix.

    Pipeline halts here until a human merges the PR (Phase 2).
    PRMerged event (Phase 3) resumes the pipeline for deployment.

    Fields:
        alert_id: Links back to the originating alert.
        pr_number: GitHub PR number.
        pr_url: Full URL to the pull request.
        branch_name: The feature branch created for this fix.
        trace_id: Propagated from FixGenerated.
    """

    alert_id: str
    pr_number: int
    pr_url: str
    branch_name: str
    trace_id: str = ""
