"""Tests for domain events."""

from sentinelai.core.events import AlertDetected, Priority, TriageComplete


class TestPriority:
    def test_all_values_exist(self):
        assert Priority.P1.value == "P1"
        assert Priority.P2.value == "P2"
        assert Priority.P3.value == "P3"
        assert Priority.P4.value == "P4"
        assert Priority.UNKNOWN.value == "UNKNOWN"

    def test_from_string(self):
        assert Priority("P1") == Priority.P1
        assert Priority("UNKNOWN") == Priority.UNKNOWN


class TestAlertDetected:
    def test_creates_with_required_fields(self):
        alert = AlertDetected(
            alert_id="test-1",
            source="test",
            service_name="auth",
            summary="error spike",
            raw_payload={"key": "value"},
        )
        assert alert.alert_id == "test-1"
        assert alert.service_name == "auth"
        assert alert.trace_id == ""  # auto-generated by pipeline, not event

    def test_timestamp_auto_generated(self):
        alert = AlertDetected(
            alert_id="test-1",
            source="test",
            service_name="auth",
            summary="error",
            raw_payload={},
        )
        assert alert.timestamp is not None


class TestTriageComplete:
    def test_creates_with_all_fields(self):
        result = TriageComplete(
            alert_id="test-1",
            severity=Priority.P2,
            root_cause_hypothesis="connection pool exhaustion",
            confidence=0.87,
            affected_services=["auth", "gateway"],
            recommended_action="increase pool size",
            ai_reasoning="detailed reasoning here",
            trace_id="abc-123",
        )
        assert result.severity == Priority.P2
        assert result.confidence == 0.87
        assert len(result.affected_services) == 2
